config/routes.rb
Todolist::Application.routes.draw do
  get "lists/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :lists do
    resources :tasks
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/newlist', to: 'list#new',             via: 'get'
  match '/editlist', to: 'list#edit',           via: 'get'
  match '/showlist', to: 'list#show',           via: 'get'
  match '/taskdelete', to: 'task#destroy',     via: 'delete'

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true, length: { maximum: 69 }
	validates :description, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :list
    default_scope -> { order('created_at DESC') }
	validates :list_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }
	validates :list_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
      SecureRandom.urlsafe_base64
    end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
  	@list = current_user.lists.build(list_params)
  	if @list.save
  	  flash[:success] = "List created!"
  	  redirect_to current_user
  	else
  	  render 'static_pages/home'
  	end
  end

  def show
    @list = List.find(params[:user_id])
    @task = @list.tasks.new
  end

  def new
    @list = current_user.lists.new
    @task = @list.tasks.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      flash[:notice] = "List Updated!"
      redirect_to current_user
    else
      flash[:error] = "Could not update list"
      redirect_to list_edit_path
    end
  end

  def destroy
    @list.destroy
    redirect_to root_url
  end

  private

    def list_params
      params.require(:list).permit(:title, :description)
    end
    def correct_user
      @list = current_user.lists.find_by(id: params[:id])
      redirect_to root_url if @list.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
   end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @list = current_user.lists.build if signed_in?
  end

  def help
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  #before_action :correct_user,   only: :destroy

def create
  @list = List.find(params[:list_id])
  @task = @list.tasks.new(task_params)
  if @task.save
    flash[:success] = "Task created!"
    redirect_to current_user
  else
  	flash[:error] = "Could not create Task"
    render 'static_pages/home'
  end
end

def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to current_user
end

private

  def task_params
    params.require(:task).permit(:content)
  end

  def correct_user
    @task = current_user.list.task.find_by(id: params[:id])
    redirect_to root_url if @task.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
    @lists = @user.lists.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @lists = @user.lists.paginate(page: params[:page])
    @lists.each do |f|
      f.tasks = f.tasks.paginate(page: params[:page])
    end
    if @lists.any?
      @list = List.new
      @task = @list.tasks.new
    else
      @list = List.new
    end
  end

  def new
  	@user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
 
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Todolist App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  #Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Todolist App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
  	!current_user.nil?
  end

  def admin?
    current_user.admin?
  end

  def current_user=(user)
  	@current_user=user
  end

  def current_list=(list)
    @current_list=list
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Todolist by Fiona Chin
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "todolist app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <% if admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/lists/_list.html.erb
<li>
  <span class="title"><b><%= list.title %></b><br>
  	<i><%= list.description %></i>
    <div class="task">
      <ol>
        <% list.tasks.each do |task| %>
        <li><span class="check"><%= check_box_tag(task.mark) %></span><%= task.content %>
          <% if current_user?(task.list.user) %>
          <%= link_to "x", list_task_path(list, task), method: :delete,
                                      data: { confirm: "You sure?" },
                                      title: task.content %></li> 
          <% end %> 
        <% end %>
      </ol>
    </div>
    <%= form_for [list, @task] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field1">
          <%= f.text_field :content, placeholder: "Create a new task..." , class: "post_field" %>
        <%= f.submit "Post", class: "btn btn-large btn-primary" %> </div>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(list.created_at) %> ago.
  </span>
  <% if current_user?(list.user) %>
     <p><%= link_to "edit", edit_list_path(list) %> | 
     <%= link_to "delete", list, method: :delete,
                                      data: { confirm: "You sure?" },
                                      title: list.title %></p>
   <% end %>
</li>

app/views/lists/edit.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render :partial => 'shared/list_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <p>Sorry Dude, You gotta sign in:</p>
  <%= link_to "Sign up now!", signup_path,
                              class: "btn btn-large btn-primary" %>
<% end %>

app/views/lists/new.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/list_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <p>Sorry Dude, You gotta sign in:</p>
  <%= link_to "Sign up now!", signup_path,
                              class: "btn btn-large btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<% provide(:title, @list.title) %>
<div class="row">
  <div class="span8">
    <h3><%= @list.title %></h3>
    <ol class="lists">
      <%= render @tasks %>
    </ol>
    <%= will_paginate @lists %>
    <%= render 'shared/task_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_list_form.html.erb
<div class = "listform">
	<%= form_for(@list) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <div class="field">
	    <%= f.text_field :title, placeholder: "List Title" %>
	  </div>
	  <div class="field">
	    <%= f.text_area :description, placeholder: "Mandatory description..." %>
	  </div>
	  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
	<% end %>
</div>

app/views/shared/_task_form.html.erb
<%= form_for (@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>	

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.lists.count, "list") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  My Name is Fiona Chin and this is my first Web Application using Ruby on Rails.  If I have to describe my web designing skills, it looks a little something like this:
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Well, you should ask a pro...jk. Please email me at flc38@cornell.edu if you have any concerns.
</p>

app/views/static_pages/home.html.erb
  <div class="center hero-unit">
    <h1>Welcome to the <br>
     Todolist App</h1>
    <h2>
      This is the home page 
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("logo.png", alt: "Fiona's App"), 'http://rubyonrails.org/' %>

app/views/tasks/_task.html.erb
<li><span class="check"><%= check_box_tag(task.mark) %></span><%= task.content %></li>  

app/views/tasks/new.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/task_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <p>Sorry, you have to sign in:</p>
  <%= link_to "Sign up now!", signup_path,
                              class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object  %>

      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => "Full Name" %>

      <%= f.label :email %>
      <%= f.text_field :email, :placeholder => "my@example.com" %>

      <%= f.label :password %>
      <%= f.password_field :password, :placeholder => "6 characters minimum"%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :placeholder => "Retype the Password" %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
      <%= render 'shared/list_form' %>
  </aside>
  <div class="span8">
      <% if @user.lists.any? %>
        <h3>My Lists (<%= @user.lists.count %>)</h3>
        <ol class="lists">
          <%= render @lists %>
        </ol>
        <%= will_paginate @lists %>
        <%= link_to "Create A New List", lists_new_path %>
      <% else %>
        <h3><%= link_to "Create A New List", lists_new_path %></h3>
      <% end %>
</div>